service: beer-store

provider:
  name: azure
  location: West Europe

plugins:
  - serverless-azure-functions

custom:
  dbname: beer-store-cosmodb

functions:
  graphql:
    handler: handler.graphql
    events:
      - http: true
        x-azure-settings:
        authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res
          methods:
            - GET
          authLevel: anonymous
          route: graphql
