service: azure-beer-store

custom:
  dbName: beerstore
  collectionName: beer_list
  storageAccountName: beerstore
  containerName: blobs

provider:
  name: azure
  location: westeurope
  environment:
    DB_NAME: ${self:custom.dbName}
    DB_COLLECTION_NAME: ${self:custom.collectionName}
    DB_HOST: ${file(./serverless.env.yml):DB_HOST}
    DB_KEY: ${file(./serverless.env.yml):DB_KEY}
    BLOB_STORAGE_CONNECTION_STRING: ${file(./serverless.env.yml):BLOB_STORAGE_CONNECTION_STRING}
    CONTAINER_NAME: ${self:custom.containerName}

plugins:
  - serverless-azure-functions

functions:
  graphql:
    handler: api.graphql
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res
          methods:
            - GET
          authLevel: anonymous
          route: graphql
  import:
    handler: blob.import
    events:
      - blob:
        x-azure-settings:
          name: item
          path: ${self:custom.containerName}/{name}.csv
          connection: BLOB_STORAGE_CONNECTION_STRING
